apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  selector: 
    matchLabels:
      app: music  
  replicas: {{ .Values.spec.replicas }}  
  template:
    metadata:
      labels:
        app: music
    spec:
      containers:
      - name: {{ .Values.spec.containers.name }}
        image: {{ .Values.spec.containers.repo}}/{{ .Values.spec.containers.image }}:{{ .Values.spec.containers.tag }}
        ports:
        - containerPort: {{ .Values.spec.containers.containerPort }}
