kind: Service      
apiVersion: v1     
metadata:
  name: {{ .Release.Name }}-service
  {{- include "spring.labels" . }}
spec:
  selector:
    {{- include "spring.labels" . | nindent 2}}
  {{ if eq .Values.ingress.enabled true }}
  type: "ClusterIP"
  {{ else }} 
  type: "LoadBalancer"
  {{ end }}
  ports:          
  - name: http    
    protocol: TCP
    port: {{ .Values.spec.port }}
    targetPort: {{ .Values.spec.targetPort }}
