apiVersion: v1
kind: Pod
metadata:
 name: nginx
spec:
 containers:
 - name: app1
   image: supergiantkir/animals:bear
   ports:
   - containerPort: 8080
   volumeMounts:
     - name: my-storage
       mountPath: /storage
 - name: springapp
   image: yanivomc/spring-music:latest
   ports:
   - containerPort: 8080
   volumeMounts:
     - name: my-storage
       mountPath: /storage


volumes:
  - name: my-storage
    HostPath: app-storage