apiVersion: v1
kind: Pod
metadata:
 name: sidecarpod
spec:
 containers:
 - name: bear
   image: supergiantkir/animals:bear
   ports:
   - containerPort: 80
   volumeMounts:
    - name: app-storage
      mountPath: /storage
 - name: moose
   image: yanivomc/spring-music:latest
   ports:
   - containerPort: 8080
   volumeMounts:
    - name: app-storage
      mountPath: /storage
 volumes:
 - name: app-storage
   hostPath:
      # directory location on host
      path: /data