apiVersion: v1
kind: Pod
metadata:
  name: myapp
spec:
  containers:
  - name: app1
    image: supergiantkir/animals:bear
    volumeMounts:
    - name: my-storage
      mountPath: /storage
  - name: app2
    image: yanivomc/spring-music:latest
    volumeMounts:
    - name: my-storage
      mountPath: /storage
  volumes:
  - name: my-storage
    hostPath:
      path: /data