metadata:
  name: spring-music
ingress:
  enabled: true
spec:
  type: LoadBalancer
  port: 80
  targetPort: 8080
  replicas: 1
  containers:
    name: spring-music
    repo: yanivomc
    image: spring-music
    tag: latest
    containerPort: 8080
dbname: alora_db
dbtable: users
